interface = "eth0"
port = 9
services = [
    "casaos-gateway",
    "casaos-message-bus",
    "casaos-user-service",
    "casaos-local-storage",
    "casaos",
    "docker",
    "nfs-kernel-server",
    "vsftpd"
]

[shutdown]
poweroff = false       # Éteindre la machine (false = arrêter services seulement)
delay_minutes = 5      # Délai avant extinction (si poweroff = true)
docker_stop = true     # Arrêter les conteneurs Docker
unexport_nfs = true    # Désactiver les exports NFS
